name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "bash prisma-generate-safe.sh"
dev = "npm run prisma -- migrate deploy && npm exec react-router dev"
